# Generated by Django 4.2.6 on 2023-10-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('descripcion', models.CharField(max_length=350, verbose_name='Descripción')),
                ('casillas', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Casillas')),
            ],
        ),
    ]
