# Generated by Django 4.2.6 on 2023-10-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('raci_participante', models.CharField(max_length=2, verbose_name='RACI')),
                ('dn_participante', models.CharField(max_length=6, verbose_name='DN')),
                ('sc_participante', models.CharField(max_length=30, verbose_name='SC')),
                ('nombres_participante', models.CharField(max_length=62, verbose_name='Nombres')),
                ('apellido_pat_participante', models.CharField(max_length=62, verbose_name='ApellidoPaterno')),
                ('apellido_mat_participante', models.CharField(max_length=62, verbose_name='ApellidoMaterno')),
            ],
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='casillas',
            new_name='casillas_elemento',
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='descripcion',
            new_name='descripcion_elemento',
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='id',
            new_name='id_elemento',
        ),
    ]
