# Generated by Django 4.2.6 on 2023-10-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='img_participante',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='ImagenParticipante'),
        ),
    ]
