# Generated by Django 4.2.6 on 2023-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_participantes_img_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='apellido_mat_participante',
            field=models.CharField(max_length=62, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='apellido_pat_participante',
            field=models.CharField(max_length=62, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='id_participante',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Identificador del participantes'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='img_participante',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto / Avatar'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='sc_participante',
            field=models.CharField(max_length=30, verbose_name='Solution Center'),
        ),
    ]
