# Generated by Django 4.2.6 on 2023-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_participantes_apellido_mat_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='id_participante',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Identificador del participante'),
        ),
    ]
